
import { HiMail } from "react-icons/hi";
import { HiUser, HiUsers } from "react-icons/hi2";
import countryList from "react-select-country-list";


const data = {
    flyers: [
        {
            id: "pub-cybersec",
            title: "Top 5 Cyber-Security Startups",
            description: "Coders HQ is working with Government entity partner to find the best local Cyber Security Startups. If you have a cyber security startup then please fill the form for a chance to work with one of our partners.",
            image: "https://images.unsplash.com/photo-1614064641938-3bbee52942c7?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1740&q=80",
            active: true,
            highlights: [
                'Coders(hq) partner are looking for cyber security startups',
                'Top 5 will be selected',
                'Chance to work with a top government agency',
                'Applications are open'
            ],
            date: {
                text: "open",
                tooltip: "There is no deadline",
            },
            details: "Please fill the form with as much detail as possible. Explain your startup and where you are in your journey.",
            form: [
                {
                    name: "First name",
                    id: "first_name",
                    type: "text",
                    required: true,
                    placeholder: "First",
                    helperText: "",
                    disabled: false,
                    readOnly: false,
                },
                {
                    name: "Last name",
                    id: "last_name",
                    type: "text",
                    required: true,
                    placeholder: "Last",
                    helperText: "",
                    disabled: false,
                    readOnly: false,
                },
                {
                    name: "Email",
                    id: "email",
                    type: "email",
                    required: true,
                    placeholder: "example@email.com",
                    helperText: "",
                    icon: HiMail,
                    disabled: false,
                    readOnly: false,  
                },
                {
                    name: "Phone",
                    id: "phone",
                    type: "text",
                    required: true,
                    placeholder: "05XXXXXXXX",
                    helperText: "",
                    disabled: false,
                    readOnly: false,
                },
                {
                    name: "Nationality",
                    id: "nationality",
                    type: "select",
                    required: true,
                    helperText: "",
                    disabled: false,
                    readOnly: false,
                    options: countryList().getLabels()
                },
                {
                    name: "Startup Name",
                    id: "name",
                    type: "text",
                    placeholder: "",
                    helperText: "",
                    required: true,
                    disabled: false,
                    readOnly: false,
                },
                {
                    name: "Website",
                    id: "website",
                    type: "text",
                    placeholder: "example.com",
                    required: false,
                    addon: "https://",
                    helperText: "If your startup has a website"
                },
                {
                    name: "Startup Details",
                    type: "textarea",
                    id: "details",
                    rows: 4,
                    helperText: "Please fill in as much detail as possible about your startup"
                },
            ]
        },
        {
            id: "amb-wintercamp",
            title: "Winter Camp Activity For Students",
            description: "Winter camp is coming and in the spirit of celebration we would like to come up with an activity for students in two age groups, one is from 11-14 and the other is from 15-18. This event is for ambassadors only where we require you to come up with a fun coding related activity and have the kids participate. The event is on the 10th of Dec",
            image: "https://images.unsplash.com/photo-1457269449834-928af64c684d?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1674&q=80",
            active: true,
            highlights: [
                'Come up with your most fun activity',
                'Help moderate and lead the event (ambassador only)',
                'Fill the form with the idea you have',
            ],
            ambassador_only: true,
            date: {
                text: "10th Dec",
                date: new Date("2022-12-10"),
                tooltip: "Deadline is on the 10th",
            },
            badgeList: [
                {
                    icon: <HiUser/>,
                    text: "ambassador",
                    tooltip: "Ambassador only",
                },
            ],
            details: "Please come up with a fun activity you think the kids would love. It must be related to coding but feel free to be creative with it. If you dont have an idea then feel free to join if you are interested either way.",
            form: [
                {
                    name: "First name",
                    id: "first_name",
                    type: "text",
                    required: true,
                    placeholder: "First",
                    helperText: "",
                    disabled: false,
                    readOnly: false,
                },
                {
                    name: "Last name",
                    id: "last_name",
                    type: "text",
                    required: true,
                    placeholder: "Last",
                    helperText: "",
                    disabled: false,
                    readOnly: false,
                },
                {
                    name: "Email",
                    id: "email",
                    type: "email",
                    required: true,
                    placeholder: "example@email.com",
                    helperText: "",
                    icon: HiMail,
                    disabled: false,
                    readOnly: false,  
                },
                {
                    name: "Phone",
                    id: "phone",
                    type: "text",
                    required: true,
                    placeholder: "05XXXXXXXX",
                    helperText: "",
                    disabled: false,
                    readOnly: false,
                },
                {
                    name: "Activity Idea",
                    type: "textarea",
                    id: "details",
                    rows: 4,
                    helperText: "Explain your idea here"
                },
            ]
        },
        {
            id: "amb-nationalday",
            title: "UAE National Day Activity",
            description: "The national day is aroud the corner and we would like to activate the Coders(hq) space. If you would like to use this time and come up with an idea realted to the national day then please suggest your idea in the form below. This activity will be lead by the ambassadors but will be for the public and to celebrate the UAE national day.",
            image: "https://images.unsplash.com/photo-1603798994946-5ea9dbacf20e?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1674&q=80",
            active: true,
            highlights: [
                'Come up with your most fun activity',
                'In celebration of the UAE National Day',
                'On Wednesday the 30th of Nov',
                'The event can last from the morning to the afternoon',
            ],
            ambassador_only: false,
            date: {
                text: "30th Nov",
                date: new Date("2022-11-30"),
                tooltip: "Deadline is on the 30th",
            },
            badgeList: [
                {
                    icon: <HiUsers/>,
                    text: "public",
                    tooltip: "Anyone can join",
                },
                {
                    icon: <HiUser/>,
                    text: "ambassador",
                    tooltip: "Ambassador lead",
                },
            ],
            details: "The event is public but must be lead by an ambassador. The event will not take place if an ambassador is not available to take the lead.",
            form: [
                {
                    name: "First name",
                    id: "first_name",
                    type: "text",
                    required: true,
                    placeholder: "First",
                    helperText: "",
                    disabled: false,
                    readOnly: false,
                },
                {
                    name: "Last name",
                    id: "last_name",
                    type: "text",
                    required: true,
                    placeholder: "Last",
                    helperText: "",
                    disabled: false,
                    readOnly: false,
                },
                {
                    name: "Email",
                    id: "email",
                    type: "email",
                    required: true,
                    placeholder: "example@email.com",
                    helperText: "",
                    icon: HiMail,
                    disabled: false,
                    readOnly: false,  
                },
                {
                    name: "Phone",
                    id: "phone",
                    type: "text",
                    required: true,
                    placeholder: "05XXXXXXXX",
                    helperText: "",
                    disabled: false,
                    readOnly: false,
                },
                {
                    name: "Activity Idea",
                    type: "textarea",
                    id: "details",
                    rows: 4,
                    helperText: "Explain your idea here"
                },
                {
                    name: "Are you an ambassador?",
                    type: "checkbox",
                    id: "ambassador",
                    helperText: ""
                },
            ]
        },
        {
            id: "amb-mawakebcarnival",
            title: "Carnival at Al Mawakeb School, Al Barsha",
            description: "The national day is aroud the corner and Al Mawakeb School, Al Barsha is hosting a carnival for its students (Grade 1-12), staff, and parents in celebration of the national day. We would like Ambassadors to contribute by volunteering in the event and coming up with acitvity ideas.",
            image: "https://images.unsplash.com/photo-1544441452-326ff5a947fd?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=870&q=80",
            active: true,
            highlights: [
                'Come up with your most fun activity',
                'In celebration of the UAE National Day',
                'On Tuesday the 29th of Nov',
                'The event will be from 8:00am to 10:30am.',
            ],
            ambassador_only: false,
            date: {
                text: "29th Nov",
                date: new Date("2022-11-29"),
                tooltip: "Deadline is on the 29th",
            },
            badgeList: [
                {
                    icon: <HiUsers/>,
                    text: "public",
                    tooltip: "Anyone can join",
                },
                {
                    icon: <HiUser/>,
                    text: "ambassador",
                    tooltip: "Ambassador lead",
                },
            ],
            details: "The PoC for the event is Muhammad Arsalan Nawazish and we require Ambassadors to volunteer in the event itself and come up with acitvities we could conduct.",
            form: [
                {
                    name: "First name",
                    id: "first_name",
                    type: "text",
                    required: true,
                    placeholder: "First",
                    helperText: "",
                    disabled: false,
                    readOnly: false,
                },
                {
                    name: "Last name",
                    id: "last_name",
                    type: "text",
                    required: true,
                    placeholder: "Last",
                    helperText: "",
                    disabled: false,
                    readOnly: false,
                },
                {
                    name: "Email",
                    id: "email",
                    type: "email",
                    required: true,
                    placeholder: "example@email.com",
                    helperText: "",
                    icon: HiMail,
                    disabled: false,
                    readOnly: false,  
                },
                {
                    name: "Phone",
                    id: "phone",
                    type: "text",
                    required: true,
                    placeholder: "05XXXXXXXX",
                    helperText: "",
                    disabled: false,
                    readOnly: false,
                },
                {
                    name: "Activity Idea",
                    type: "textarea",
                    id: "details",
                    rows: 4,
                    helperText: "Explain your idea here"
                },
                {
                    name: "Are you an ambassador?",
                    type: "checkbox",
                    id: "ambassador",
                    helperText: "Tick if true"
                },
            ]
        },
        {
            id: "pub-gamingtalent",
            title: "Call to UAE Gaming Talent",
            description: "We are looking for local gaming talent that are within the gaming field. If are a designer, 3D artist, developer or have experience in any field related to gaming then please sign up below. The top 100 will be picked for a special course with one of our partners to be trained with one of the top gaming companies in the world.",
            image: "https://images.unsplash.com/photo-1511512578047-dfb367046420?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1742&q=80",
            active: true,
            highlights: [
                'This is a call to: Designers',
                'Developers',
                '3D Artists',
                'Animators',
                'Story Writers',
                'And any other field related to game development',
            ],
            ambassador_only: false,
            date: {
                text: "open",
                // date: new Date("2022-11-29"),
                tooltip: "This project has no deadline",
            },
            badgeList: [
                {
                    icon: <HiUsers/>,
                    text: "public",
                    tooltip: "Anyone can join",
                },
            ],
            details: "Please fill in the form with your details and your field. We will get back to you if you are selected among the top 100.",
            form: [
                {
                    name: "First name",
                    id: "first_name",
                    type: "text",
                    required: true,
                    placeholder: "First",
                    helperText: "",
                    disabled: false,
                    readOnly: false,
                },
                {
                    name: "Last name",
                    id: "last_name",
                    type: "text",
                    required: true,
                    placeholder: "Last",
                    helperText: "",
                    disabled: false,
                    readOnly: false,
                },
                {
                    name: "Email",
                    id: "email",
                    type: "email",
                    required: true,
                    placeholder: "example@email.com",
                    helperText: "",
                    icon: HiMail,
                    disabled: false,
                    readOnly: false,  
                },
                {
                    name: "Phone",
                    id: "phone",
                    type: "text",
                    required: true,
                    placeholder: "05XXXXXXXX",
                    helperText: "",
                    disabled: false,
                    readOnly: false,
                },
                {
                    name: "Nationality",
                    id: "nationality",
                    type: "select",
                    required: true,
                    helperText: "",
                    disabled: false,
                    readOnly: false,
                    options: countryList().getLabels()
                },
                {
                    name: "Highest Academic Qualification",
                    id: "academic",
                    type: "text",
                    required: true,
                    placeholder: "Masters in Computer Science",
                    helperText: "Please fill in your highest qualification",
                    disabled: false,
                    readOnly: false,
                },
                {
                    name: "University",
                    id: "university",
                    type: "text",
                    required: false,
                    placeholder: "Khalifa University",
                    helperText: "Which university did you graduate from",
                    disabled: false,
                    readOnly: false,
                },
                {
                    name: "Specialisation Field",
                    id: "field",
                    type: "text",
                    required: true,
                    placeholder: "3D Artist, Sound Designer",
                    helperText: "Which gaming related field do you have experience in",
                    disabled: false,
                    readOnly: false,
                },
                {
                    name: "Years of Experience",
                    id: "experience_years",
                    type: "number",
                    required: false,
                    placeholder: "3",
                    helperText: "Years of experience in your field",
                    disabled: false,
                    readOnly: false,
                }
            ]
        },
    ],
}

export {data}
